name: favorita_sales_forecasting

channels:
  - defaults

dependencies:
  - python=3.10
  - numpy=1.21
  - pip=21.2
  - pandas=1.4
  - matplotlib=3.5
  - seaborn=0.11
  - scikit-learn=1.0
  - xgboost=1.5
  - pip:
    - ipykernel
    - jupyterlab